### ISSUE TITLE
slack-ruby-bot > 0.7.0 doesn't work with this gem

### ISSUE THREAD

**Issue by kstole** [slack-ruby/newrelic-slack-ruby-bot#1]
I'm trying to hook up my SlackRubyBot app with New Relic and seem to be getting no results. I have a `newrelic.yml` file in the root directory and I've added `newrelic-slack-ruby-bot` to the Gemfile. I also tried adding `NewRelic::Agent.manual_start`, which required me to `require 'newrelic-slack-ruby-bot'` above it, but nothing seems to be happening. Am I missing something?

**Comment by dblock** [comment]
Maybe check another bot where it works, eg. https://github.com/dblock/slack-sup?

I just throw in newrelic.yml with the right license keys and voila.

**Comment by kstole** [comment]
Is this gem only meant to be used with [slack-ruby-bot-server](https://github.com/slack-ruby/slack-ruby-bot-server)?
I found that to get it to work, I had to
- `require 'newrelic-slack-ruby-bot'` in `config.ru` before calling `NewRelic::Agent.manual_start`
- change `::SlackRubyBot::Server` on [L18 of instrumentation.rb](https://github.com/slack-ruby/newrelic-slack-ruby-bot/blob/master/lib/newrelic-slack-ruby-bot/instrumentation.rb#L18) to `::SlackRubyBot::Client`

**Comment by dblock** [comment]
No, it's meant to be used with `slack-ruby-bot`, so https://github.com/slack-ruby/slack-ruby-bot/blob/master/lib/slack-ruby-bot/server.rb, hence the name.

I am not sure whether a library like this should be dealing at client level... thoughts?

**Comment by kstole** [comment]
Maybe I was trying to get it to do something it wasn't meant for.
I got this error in my New Relic log:
```
ERROR : Error while installing slack_ruby_bot_instrumentation instrumentation:
ERROR : NameError: undefined method `message' for class `SlackRubyBot::Server'
```
I found that `SlackRubyBot::Client` had a method `message` but then I had to change the parameters from `(client, data)` to `(options)`. Is this actually supposed to be starting the transaction at `SlackRubyBot::Hooks::Message`? I see that has method `call(client, data)`, which matches the instrumentation.

**Comment by dblock** [comment]
I can take a look later, but maybe there was a lot of refactoring in the underlying library. If you want to help, do specs pass in this library with the latest version of slack-ruby-bot?

**Comment by kstole** [comment]
No, I'm getting the same error
```
1) NewRelic::Agent::Instrumentation perform_action_with_newrelic_trace
     Failure/Error: subject.message(client, message: 'message', text: 'hi')
     
     NoMethodError:
       undefined method `message' for #<SlackRubyBot::Server:0x007fc20f8f20b8>
     # ./spec/newrelic-slack-ruby-bot/instrumentation_spec.rb:14:in `block (2 levels) in <top (required)>'
```

**Comment by dblock** [comment]
Looks like we broke it in https://github.com/slack-ruby/slack-ruby-bot/commit/6ff89e5d0c6b7904521433c580e9f98d0b42b44b#diff-5c7b47ad09371ab4da73196486c69174, cc: @dramalho.

There're two things to do:

1) Find the last version with which tests pass, I believe it's 0.7.0. Lock .gemspec to that max and release a patch.

2) Fix the code.

Want to help out @kstole? Feel free to make a pull request for (1).

**Comment by dramalho** [comment]
I'm sorry, the statutory warranty for that commit has expired :)

Kidding, not sure what's going on, what's this `./spec/newrelic-slack-ruby-bot/instrumentation_spec.rb` and who should be responding to `.message` ?

**Comment by dramalho** [comment]
[This spec](https://github.com/slack-ruby/newrelic-slack-ruby-bot/blob/master/spec/newrelic-slack-ruby-bot/instrumentation_spec.rb) got it  - I failed to notice this was the right repo all along.

**Comment by dblock** [comment]
@dramalho No worries, I only cc-ed you for general awareness, no expectations :)

**Comment by dramalho** [comment]
Nah, it's fine, just wanted to figure it out - it's been a while :) . That particular spec you showed can't pass because whereas before hooks implemented the events by naming the method the same way as the method - i.e. `def message` - which would then be included into `SlackRubyBot::Server` , now they are classes who, regardless of name, are added into a registry and mapped to even types . 

(wow, complicated sentence)

In the case of that spec alone, yes, it's broken simply because the method `message` in the server no longer exists. 

Maybe that also goes and explains why NewRelic doesn't seem to be triggered ?

**Comment by kstole** [comment]
@dramalho correct, that's why it's getting
```
NameError: undefined method `message' for class `SlackRubyBot::Server'
```

**Comment by dramalho** [comment]
Yeah, I guess the `alias_method` [stuff](https://github.com/slack-ruby/newrelic-slack-ruby-bot/blob/a433dd478de1c273a3e5a624376a4c38fd758b1f/lib/newrelic-slack-ruby-bot/instrumentation.rb#L27) needs a different approach as that definitely isn't available like that anymore. 

If all this is instrumentalizing is messages we should probably move that into the default Message hook class (not great to be honest as that's just one default implementation that can be swapped out) or we can maybe, like you said, move it into the client and instrumentalize all the events that come in?

(sorry if I'm just pointing very obvious things, like I said, it's been a while :), memories have faded )

**Comment by kstole** [comment]
I'm not sure why `alias_method` wouldn't work. I just made a few changes and this is working:
```ruby
::SlackRubyBot::Hooks::Message.class_eval do
  include ::NewRelic::Agent::Instrumentation::ControllerInstrumentation

  def message_with_new_relic(client, data)
    perform_action_with_newrelic_trace(name: 'call', category: 'OtherTransaction/Slack') do
      message_without_new_relic(client, data)
    end
  end

  alias_method :message_without_new_relic, :call
  alias_method :call, :message_with_new_relic
end
```
I can make a PR if this seems like a reasonable way to fix it.

**Comment by kstole** [comment]
What I really want is to separate transactions for different commands in NewRelic. I found a way to do that while using this message tracer is to rename the transaction in each individual command block by adding this line (replacing class/command names):
```ruby
NewRelic::Agent.set_transaction_name('MyBot::Commands::ClassName/command_name')
```
Anyone have an idea how this could be included in this gem?

**Comment by dramalho** [comment]
Yeah, if you add it to the Message class like you did then yes, it works . Just know that it's entirely possible to unassign that particular event class and use a different one, which was my point about maybe not instrumentalizing the particular message implementation. 

re: instrumentalizing all the events ,I think that's a better approach myself - I guess we could hook into the client itself as that handles events . I can't look at the code now, but I think that's where we register the hooks, so seems like a good place.

Either way, this gem definitely needs to be locked down to the working version of `slack-ruby-bot` before we move to make it better :)

**Comment by kstole** [comment]
@dblock For the patch, do I need to fork and then create a PR or is there a simpler method?

**Comment by dblock** [comment]
Yes, please see https://github.com/slack-ruby/newrelic-slack-ruby-bot/blob/master/CONTRIBUTING.md.
